// Date: 8/15/13 1:24:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package sheenrox82.RioV.src.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDove extends ModelBase
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;

	public ModelDove()
	{
		textureWidth = 64;
		textureHeight = 32;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 2, 2, 4);
		Shape1.setRotationPoint(-1F, 20F, 0F);
		Shape1.setTextureSize(64, 32);
		Shape1.mirror = true;
		setRotation(Shape1, -0.4537856F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 7);
		Shape2.addBox(0F, 0F, 0F, 4, 0, 3);
		Shape2.setRotationPoint(0F, 20F, 0F);
		Shape2.setTextureSize(64, 32);
		Shape2.mirror = true;
		setRotation(Shape2, -0.4537856F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 0, 7);
		Shape3.addBox(0F, 0F, 0F, 4, 0, 3);
		Shape3.setRotationPoint(0F, 20F, 0F);
		Shape3.setTextureSize(64, 32);
		Shape3.mirror = true;
		setRotation(Shape3, 0.4537856F, 0F, 3.141593F);
		Shape4 = new ModelRenderer(this, 0, 11);
		Shape4.addBox(0F, 0F, 0F, 4, 0, 3);
		Shape4.setRotationPoint(-2F, 22F, 3F);
		Shape4.setTextureSize(64, 32);
		Shape4.mirror = true;
		setRotation(Shape4, -0.1570796F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 0, 15);
		Shape5.addBox(0F, 0F, 0F, 2, 2, 2);
		Shape5.setRotationPoint(-1F, 19F, -2F);
		Shape5.setTextureSize(64, 32);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par7Entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, par7Entity);
		Shape2.rotateAngleY = (MathHelper.cos(f * 1F) * 0.277F * f1);
		Shape3.rotateAngleY = (MathHelper.cos(f * 1F) * 0.277F * f1);
	}

}
